trigger:
  tags:
    include:
      - 'v*'

  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

jobs:
  - job: lint
    displayName: Lint
    pool:
      vmImage: 'ubuntu-16.04'
    container: rust:latest
    steps:
      - script: rustup component add rustfmt clippy-preview
        displayName: Install
      - script: cargo fmt -- --color=never --check
        displayName: Format
      - script: cargo clippy --color=never --all --all-features
        displayName: Clippy
  
  - job: integrate
    displayName: Integrate
    strategy:
      matrix:
        windows-stable:
          imageName: 'vs2017-win2016'
          rustup_toolchain: stable
        mac-stable:
          imageName: 'macos-10.13'
          rustup_toolchain: stable
        linux-stable:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: stable
        linux-beta:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: beta
        linux-nightly:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: nightly
    pool:
      vmImage: $(imageName)
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install Rust (Unix)
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: Install Rust (Windows)
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - script: cargo build --all --examples --tests --benches
        displayName: Build
      - script: cargo test --all
        displayName: Test

  - job: deploy
    displayName: Deploy
    dependsOn:
      - lint
      - integrate
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: 'ubuntu-16.04'
    container: rust:latest
    steps:
      - task: DownloadSecureFile@1
        displayName: Download Credentials
        name: credentials
        inputs:
          secureFile: credentials
      - script: mkdir -p ~/.cargo && cp $(credentials.secureFilePath) /usr/local/cargo/credentials
        displayName: Install Credentials
      - script: cargo publish --color=never
        displayName: Publish to crates.io
